-- ==========================================
-- SCRIPT DE INICIALIZAÇÃO BOMBA (AGROFORGE)
-- Rode isto no SQL Editor do Supabase
-- ==========================================

-- 1. Criação das Tabelas
CREATE TABLE IF NOT EXISTS public.produtos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT,
  mainCategory TEXT,
  price DECIMAL(10,2) DEFAULT 0,
  image TEXT,
  description TEXT,
  detailedDescription TEXT,
  stock INT DEFAULT 0,
  rating TEXT DEFAULT '0.0',
  reviews INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.blog_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  abstract TEXT,
  content TEXT,
  image_url TEXT,
  author TEXT,
  category TEXT,
  tags TEXT,
  published_date TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.fornecedores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  cnpj TEXT,
  contact TEXT,
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.media_items (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  size TEXT,
  folder TEXT DEFAULT 'Geral',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Configurações de RLS (Row Level Security)

-- Produtos: Qualquer um pode criar e ler (Apenas para testes, proteja depois)
ALTER TABLE public.produtos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public profiles are viewable by everyone" ON public.produtos FOR SELECT USING (true);
CREATE POLICY "Enable insert for everyone" ON public.produtos FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for everyone" ON public.produtos FOR UPDATE USING (true);
CREATE POLICY "Enable delete for everyone" ON public.produtos FOR DELETE USING (true);

-- Blog Posts: Qualquer um pode criar e ler
ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public blog viewable by everyone" ON public.blog_posts FOR SELECT USING (true);
CREATE POLICY "Enable insert for everyone" ON public.blog_posts FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for everyone" ON public.blog_posts FOR UPDATE USING (true);
CREATE POLICY "Enable delete for everyone" ON public.blog_posts FOR DELETE USING (true);

-- Fornecedores: Qualquer um pode criar e ler
ALTER TABLE public.fornecedores ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public suppliers viewable by everyone" ON public.fornecedores FOR SELECT USING (true);
CREATE POLICY "Enable insert for everyone" ON public.fornecedores FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for everyone" ON public.fornecedores FOR UPDATE USING (true);
CREATE POLICY "Enable delete for everyone" ON public.fornecedores FOR DELETE USING (true);

-- Media Items: Qualquer um pode criar e ler (Apenas para testes, proteja depois)
ALTER TABLE public.media_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public media viewable by everyone" ON public.media_items FOR SELECT USING (true);
CREATE POLICY "Enable insert for everyone" ON public.media_items FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable delete for everyone" ON public.media_items FOR DELETE USING (true);

-- 3. Criação do Bucket de Imagens
-- Nota: Isso cria o bucket se a extensão storage_admin estiver habilitada, 
-- caso contrário você pode criar manualmente com o nome "media" marcando como 'Public'.
insert into storage.buckets (id, name, public)
values ('media', 'media', true)
on conflict (id) do nothing;

create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'media' );

create policy "Public inserts"
  on storage.objects for insert
  with check ( bucket_id = 'media' );

create policy "Public updates"
  on storage.objects for update
  using ( bucket_id = 'media' );

create policy "Public deletes"
  on storage.objects for delete
  using ( bucket_id = 'media' );
